version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/sanskar/react-app/node_modules
      - .:/home/sanskar/react-app
  test-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/sanskar/react-app/node_modules
      - .:/home/sanskar/react-app
    command: ["npm", "run", "test"]